name: Create Top Languages

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run custom action
        uses: gouef/githubtoplanguages@main
        with:
          botName: "Jan Galek"
          botEmail: "ghome.cz@gmail.com"
          user: "JanGalek"
          limit: 6
          ignoredOrgsFlag: "wowmua,EpicGames"
          ignoredReposFlag: "wowmua/Maps"
          ignoredLangsFlag: "OASv3-yaml,OASv2-yaml,Gettext Catalog,YAML,JSON,CSS,Go Template,HTML,Latte,Makefile,MiniYAML,SCSS,Dockerfile,SVG,Meson"
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
