name: Create Top Languages

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run custom action
        uses: gouef/githubtoplanguages@main
        with:
          botName: "Jan Galek"
          botEmail: "ghome.cz@gmail.com"
          user: "JanGalek"
          limit: 8
          ignoredOrgsFlag: "wowmua,EpicGames,Go2speak,gothicuef"
          ignoredReposFlag: "wowmua/Maps,TroiaStudio/blizzard-api"
          ignoredLangsFlag: "OASv3-yaml,OASv2-yaml,Gettext Catalog,YAML,JSON,Makefile,MiniYAML,SCSS,Dockerfile,SVG,Meson"
          withStreak: "true"
          showStats: "true"
          statsFeatures: "commits,prs,issues,stars,repos,followers"
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
